version : "3"
services:
  wink-blog-gcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wink-blog-gcp
    depends_on:
      - wink-blog-gcp-pg
    volumes:
      - .:/var/www/html
    restart: always
    environment:
      APP_NAME: 'wink-blog-gcp'
#      APP_ENV: 'local'
#      APP_DEBUG: 'true'
      APP_URL: 'http://210.101.1.1'
      DB_CONNECTION: 'pgsql'
    networks:
      wink-blog-gcp-network:
        ipv4_address: 210.101.1.1

  wink-blog-gcp-pg:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: wink_blog_gcp
    container_name: wink-blog-gcp-pg
    volumes:
      - wink-blog-gcp-pg-disk:/var/lib/postgres
    networks:
      wink-blog-gcp-network:
        ipv4_address: 210.101.1.2

# On-disk storage of DB data, when containers are stopped/removed
volumes:
  wink-blog-gcp-pg-disk: {}

# Local network for services running using this docker-compose config
networks:
  wink-blog-gcp-network:
    ipam:
      driver: default
      config:
        - subnet: 210.101.0.0/16
